export const FETCH_GAMES_START = 'FETCH_GAMES_START';
export const FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS';
export const FETCH_GAMES_FAILURE = 'FETCH_GAMES_FAILURE';

export const FETCH_GAME_BY_ID_START = 'FETCH_GAME_BY_ID_START';
export const FETCH_GAME_BY_ID_SUCCESS = 'FETCH_GAME_BY_ID_SUCCESS';
export const FETCH_GAME_BY_ID_FAILURE = 'FETCH_GAME_BY_ID_FAILURE';

export const ADD_GAME_TO_CART = 'ADD_GAME_TO_CART';

export const SEARCH_GAME = 'SEARCH_GAME';

export const FETCH_CATEGORIES_START = 'FETCH_CATEGORIES_START';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';
